- name: Bastion
  hosts: tag__Batch
  gather_facts: false
  become: true

  tasks:
    - name: Show local facts
      debug:
        msg: >
          OS: {{ ansible_local.system_info.os_family }},
          Arch: {{ ansible_local.system_info.architecture }},
          Hostname: {{ ansible_local.system_info.hostname }}

    - name: Run a test command
      ansible.builtin.command: echo "Hello from facts!" > /tmp/fact-test.txt
      changed_when: false
