name: 'Ansible Lint'
description: 'Run ansible-lint on the Ansible playbooks See: https://github.com/ansible/ansible-lint/blob/main/action.yml'

on:
  push:

permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)

jobs:
  ansible-lint:
    name: 'Ansible Lint'
    runs-on: ubuntu-24.04

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Run ansible-lint
    # See: https://github.com/marketplace/actions/run-ansible-lint
    - name: Run ansible-lint
      uses: ansible/ansible-lint@main
      # optional (see below):
      with:
        args: ""
        setup_python: "true"
        working_directory: ""
        requirements_file: "requirements.yaml"

